//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projectExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ..\...
        /// </summary>
        internal static string FilePathDefault {
            get {
                return ResourceManager.GetString("FilePathDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create project.
        /// </summary>
        internal static string Form1_btCreateProject {
            get {
                return ResourceManager.GetString("Form1_btCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recreate folder.
        /// </summary>
        internal static string Form1_btnReCreateFolder {
            get {
                return ResourceManager.GetString("Form1_btnReCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reload.
        /// </summary>
        internal static string Form1_btnReloadPath {
            get {
                return ResourceManager.GetString("Form1_btnReloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Form1_btnSearchFolder {
            get {
                return ResourceManager.GetString("Form1_btnSearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tag another folder.
        /// </summary>
        internal static string Form1_btnTagAnotherFolder {
            get {
                return ResourceManager.GetString("Form1_btnTagAnotherFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group.
        /// </summary>
        internal static string Form1_chGroup {
            get {
                return ResourceManager.GetString("Form1_chGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a permissions.
        /// </summary>
        internal static string Form1_chPermissions {
            get {
                return ResourceManager.GetString("Form1_chPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There has been an exception.
        /// </summary>
        internal static string Form1_Error_Exception_caption {
            get {
                return ResourceManager.GetString("Form1_Error_Exception_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No name.
        /// </summary>
        internal static string Form1_Error_NoName_caption {
            get {
                return ResourceManager.GetString("Form1_Error_NoName_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No name was specified.
        /// </summary>
        internal static string Form1_Error_NoName_message {
            get {
                return ResourceManager.GetString("Form1_Error_NoName_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project exists.
        /// </summary>
        internal static string Form1_Error_ProjectExists_caption {
            get {
                return ResourceManager.GetString("Form1_Error_ProjectExists_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A project with the same name already exists, do you want to redo the project?.
        /// </summary>
        internal static string Form1_Error_ProjectExists_message {
            get {
                return ResourceManager.GetString("Form1_Error_ProjectExists_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There has been in the xml.
        /// </summary>
        internal static string Form1_Error_XmlInterpreter_caption {
            get {
                return ResourceManager.GetString("Form1_Error_XmlInterpreter_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The XML root has no children..
        /// </summary>
        internal static string Form1_Error_XmlInterpreter_ExeptionXMLHasNotChildNodes_message {
            get {
                return ResourceManager.GetString("Form1_Error_XmlInterpreter_ExeptionXMLHasNotChildNodes_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The XML does not have a root named &quot;rood&quot;.
        /// </summary>
        internal static string Form1_Error_XmlInterpreter_ExeptionXMLNotRoot_message {
            get {
                return ResourceManager.GetString("Form1_Error_XmlInterpreter_ExeptionXMLNotRoot_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error executing the XML.
        /// </summary>
        internal static string Form1_Error_XmlInterpreter_message {
            get {
                return ResourceManager.GetString("Form1_Error_XmlInterpreter_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML not found.
        /// </summary>
        internal static string Form1_Error_XMLNotFound_caption {
            get {
                return ResourceManager.GetString("Form1_Error_XMLNotFound_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An XML was not found in the project path: .
        /// </summary>
        internal static string Form1_Error_XMLNotFound_message {
            get {
                return ResourceManager.GetString("Form1_Error_XMLNotFound_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New project.
        /// </summary>
        internal static string Form1_InputBox_GetNameNewProject_caption {
            get {
                return ResourceManager.GetString("Form1_InputBox_GetNameNewProject_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the name of the new project.
        /// </summary>
        internal static string Form1_InputBox_GetNameNewProject_message {
            get {
                return ResourceManager.GetString("Form1_InputBox_GetNameNewProject_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, target folder: .
        /// </summary>
        internal static string Form1_lbErrorLink {
            get {
                return ResourceManager.GetString("Form1_lbErrorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parent folder path of all projects: .
        /// </summary>
        internal static string Form1_lblParentFolder {
            get {
                return ResourceManager.GetString("Form1_lblParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xml files (*.xml)|*.xmlML.
        /// </summary>
        internal static string Form1_OpenFileDialog_SelectFileXML {
            get {
                return ResourceManager.GetString("Form1_OpenFileDialog_SelectFileXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        internal static string Form1_permission_d {
            get {
                return ResourceManager.GetString("Form1_permission_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a strange permission.
        /// </summary>
        internal static string Form1_permission_default {
            get {
                return ResourceManager.GetString("Form1_permission_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Access.
        /// </summary>
        internal static string Form1_permission_f {
            get {
                return ResourceManager.GetString("Form1_permission_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify access.
        /// </summary>
        internal static string Form1_permission_m {
            get {
                return ResourceManager.GetString("Form1_permission_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sin acceso.
        /// </summary>
        internal static string Form1_permission_n {
            get {
                return ResourceManager.GetString("Form1_permission_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a read only access.
        /// </summary>
        internal static string Form1_permission_r {
            get {
                return ResourceManager.GetString("Form1_permission_r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a read and execute access.
        /// </summary>
        internal static string Form1_permission_rx {
            get {
                return ResourceManager.GetString("Form1_permission_rx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a write only access.
        /// </summary>
        internal static string Form1_permission_w {
            get {
                return ResourceManager.GetString("Form1_permission_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Projects.
        /// </summary>
        internal static string Form1_title {
            get {
                return ResourceManager.GetString("Form1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ^(?:[a-zA-Z]\:|\\\\[\w\.]+\\[\w.$]+)\\(?:[\w]+\\)*\w([\w.])+$.
        /// </summary>
        internal static string Regex_FilePath {
            get {
                return ResourceManager.GetString("Regex_FilePath", resourceCulture);
            }
        }
    }
}
