//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projectExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        internal static string Form1_btCreateProject {
            get {
                return ResourceManager.GetString("Form1_btCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Form1_btnReloadPath {
            get {
                return ResourceManager.GetString("Form1_btnReloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Form1_btnSearchFolder {
            get {
                return ResourceManager.GetString("Form1_btnSearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grup.
        /// </summary>
        internal static string Form1_chGrup {
            get {
                return ResourceManager.GetString("Form1_chGrup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permissions.
        /// </summary>
        internal static string Form1_chPermissions {
            get {
                return ResourceManager.GetString("Form1_chPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        internal static string Form1_Error_NoName_caption {
            get {
                return ResourceManager.GetString("Form1_Error_NoName_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name was specified.
        /// </summary>
        internal static string Form1_Error_NoName_message {
            get {
                return ResourceManager.GetString("Form1_Error_NoName_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project exists.
        /// </summary>
        internal static string Form1_Error_ProjectExists_caption {
            get {
                return ResourceManager.GetString("Form1_Error_ProjectExists_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with the same name already exists, do you want to redo the project?.
        /// </summary>
        internal static string Form1_Error_ProjectExists_message {
            get {
                return ResourceManager.GetString("Form1_Error_ProjectExists_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been in the xml.
        /// </summary>
        internal static string Form1_Error_XmlInterpreter_caption {
            get {
                return ResourceManager.GetString("Form1_Error_XmlInterpreter_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML root has no children..
        /// </summary>
        internal static string Form1_Error_XmlInterpreter_ExepcionXMLHasNotChildNodes_message {
            get {
                return ResourceManager.GetString("Form1_Error_XmlInterpreter_ExepcionXMLHasNotChildNodes_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML does not have a root named &quot;rood&quot;.
        /// </summary>
        internal static string Form1_Error_XmlInterpreter_ExepcionXMLNotRoot_message {
            get {
                return ResourceManager.GetString("Form1_Error_XmlInterpreter_ExepcionXMLNotRoot_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error executing the XML.
        /// </summary>
        internal static string Form1_Error_XmlInterpreter_message {
            get {
                return ResourceManager.GetString("Form1_Error_XmlInterpreter_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML not found.
        /// </summary>
        internal static string Form1_Error_XMLNotFound_caption {
            get {
                return ResourceManager.GetString("Form1_Error_XMLNotFound_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XML was not found in the project path: {0}.
        /// </summary>
        internal static string Form1_Error_XMLNotFound_message {
            get {
                return ResourceManager.GetString("Form1_Error_XMLNotFound_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        internal static string Form1_InputBox_GetNameNewProject_caption {
            get {
                return ResourceManager.GetString("Form1_InputBox_GetNameNewProject_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the new project.
        /// </summary>
        internal static string Form1_InputBox_GetNameNewProject_message {
            get {
                return ResourceManager.GetString("Form1_InputBox_GetNameNewProject_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent folder path of all projects: .
        /// </summary>
        internal static string Form1_lblParentFolder {
            get {
                return ResourceManager.GetString("Form1_lblParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml files (*.xml)|*.xmlML.
        /// </summary>
        internal static string Form1_OpenFileDialog_SelectFileXML {
            get {
                return ResourceManager.GetString("Form1_OpenFileDialog_SelectFileXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Form1_tilte {
            get {
                return ResourceManager.GetString("Form1_tilte", resourceCulture);
            }
        }
    }
}
